blog/models.py
from flask_sqlalchemy import SQLAlchemy
import uuid
import datetime

db = SQLAlchemy()


def uuid4():
    return str(uuid.uuid4())


class Page(db.Model):
    __tablename__ = 'pages'
    id = db.Column(db.String, primary_key=True, default=uuid4)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    slug = db.Column(db.String, unique=True, nullable=False)
    is_published = db.Column(db.Boolean, default=True)
    title = db.Column(db.String, nullable=False)
    intro = db.Column(db.String)
    text = db.Column(db.String, nullable=False)

    @staticmethod
    def published():
        return Page.query.filter_by(is_published=True)

blog/views.py
import functools
from sqlalchemy import desc
from flask import Blueprint
from flask.helpers import get_env
from flask import (url_for, redirect, render_template,
                   abort, flash, session, request)
from flask_wtf import FlaskForm, RecaptchaField
from wtforms_alchemy import model_form_factory
from flask.globals import current_app
from models import Page, db
from wtforms import StringField, TextAreaField, validators as v, PasswordField
from flask_mail import Mail, Message


bp = Blueprint('blog', 'blog')

mail = Mail()

ModelForm = model_form_factory(FlaskForm)


class ContactForm(FlaskForm):
    email = StringField('Your email', [v.Email(), v.DataRequired()])
    name = StringField('Your name', [v.DataRequired()])
    message = TextAreaField('Your message', [v.DataRequired()])
    recaptcha = RecaptchaField()


class LoginForm(FlaskForm):
    username = StringField(
        'Username', [v.Email(), v.DataRequired(), v.EqualTo])
    password = PasswordField('Password', [v.DataRequired()])
    recaptcha = RecaptchaField()


class PageForm(ModelForm):
    class Meta:
        model = Page


def login_required(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        if (
            session.get('auth_correct', False)
            or get_env() == 'testing'
        ):
            return fn(*args, **kwargs)
        return redirect(url_for('blog.admin', next=request.path))
    return inner


@bp.route('/admin/pages/<id>', methods=['POST', 'GET'])
@login_required
def admin_pages(id=None):
    obj = (Page.query.get(id) if id else None) or Page()
    form = PageForm(obj=obj)

    if form.validate_on_submit():
        form.populate_obj(obj)
        db.session.add(obj)
        db.session.commit()
        flash('Saved', 'success')
        return redirect(url_for('blog.admin_pages', id=obj.id))

    cntx = dict(
        page=obj,
        form=form,
        id=id,
        nav_suppressed=True,
    )
    return render_template('admin/page_edit.html', **cntx)


@bp.route('/admin/pages/')
@login_required
def admin_pages_list(id=None):
    cntx = dict(
        pages=Page.query.order_by(desc(Page.created_at)).all(),
        nav_suppressed=True,
    )
    return render_template('admin/page_list.html', **cntx)


@bp.route('/admin/login', methods=['POST', 'GET'])
def login():
    next_url = request.args.get('next', url_for('blog.admin_pages_list'))
    form = LoginForm()
    if session.get('auth_correct'):
        return redirect(next_url)

    if form.validate_on_submit():
        if (
            current_app.config['BLOG_EMAIL'] == form.username.data and
            current_app.config['BLOG_USERPWD'] == form.password.data
        ):
            session['auth_correct'] = True
            return redirect(next_url)

    cntx = {
        'form': form,
        'page': {
            'title': 'Login Page'
        }}
    return render_template('front/login.html', **cntx)


@bp.route('/admin/logout')
@login_required
def admin_logout():
    del session['auth_correct']
    return redirect(request.args.get('next', '/'))


@bp.route('/')
@bp.route('/p/<int:num>')
def home(num=0):
    offset = int(current_app.config['BLOG_PAGINATE_PAGE_COUNT'])
    cntx = {
        'page': Page.published().first(),
        'pagination': (
            Page.published()
            .filter(Page.slug != '/')
            .order_by(desc(Page.created_at))
            .paginate(num, offset, False)
        ),
    }
    return render_template('front/index.html', **cntx)


@bp.route('/<path:slug>.html')
def page(slug='/'):
    preview = request.args.get('preview') is not None
    page = Page.query.filter(Page.slug == slug).first()
    if page is None or (not page.is_published and not preview):
        abort(404)

    cntx = dict(page=page)
    if page:
        return render_template('front/page.html', **cntx)


@bp.route('/contact', methods=['POST', 'GET'])
def contact():
    form = ContactForm()
    success_send = False
    if form.validate_on_submit():
        host = request.headers.get('Host', '<no host>')
        msg = Message(f'Incoming message from [{host}]',
                      sender=form.email.data,
                      recipients=[current_app.config['BLOG_CONTACT_EMAIL']],
                      body=form.message.data
                      )
        mail.send(msg)
        success_send = True

    cntx = {
        'form': form,
        'success_send': success_send,
        'page': {
            'title': 'Contact Me',
            'intro': 'Have questions? I have answers.'
        }
    }
    return render_template('front/contact.html', **cntx)

blog/templates/front/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ config.GOOGLE_ANALITICS_GTAG }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{config.GOOGLE_ANALITICS_GTAG}}');
</script>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{{title}}</title>
  <!-- Bootstrap core CSS -->
  <link href="/static/front/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="/static/front/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="/static/front/css/clean-blog.css" rel="stylesheet">
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
    <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if session.auth_correct %}
          {% if page.id %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('blog.admin_pages', id=page.id)}}">Edit</a>
              </li>

          {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('blog.admin_pages_list')}}">Admin</a>
            </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="/about.html?preview=yes">About Me</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{url_for('blog.contact')}}">Contact</a>
          </li>

          <li class="nav-item">
          {% if session.auth_correct %}
            <a class="nav-link" href="{{url_for('blog.admin_logout')}}">Sign Out</a>
          {% else %}
            <a class="nav-link" href="{{url_for('blog.login')}}">Sign In</a>
          {% endif %}

          </li>
        </ul>
      </div>
    </div>
  </nav>

{% block header %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/static/img/{{background_image if background_image is defined else "background.jpg"}}');" >
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{page.title}}</h1>
            <span class="subheading">{{page.intro}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  {% endblock header %}

<!-- Main Content -->
  <div class="container">
    <div class="row">

      <div class="col-lg-10 col-md-12 mx-auto">
      {% block content %}
        {% for _page in pagination.items %}
          <div class="post-preview">
            <a href="{{url_for('blog.page', slug=_page.slug)}}">
              <h2 class="post-title">
                {{_page.title}}
              </h2>
              <h3 class="post-subtitle">
                {{_page.intro}}
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="{{config.BLOG_GITHUB_LINK}}">{{config.BLOG_AUTHOR_NAME}}</a>
              on {{_page.created_at.strftime("%B %d, %Y")}}</p>
          </div>
          <hr>
        {% endfor %}

        <div class="clearfix">
                <!-- Pager -->
            {% if pagination.has_next %}
                <a class="btn btn-primary float-right" href="{{url_for('blog.home', num=pagination.next_num)}}">Older Posts &rarr;</a>
            {% endif %}
            {% if pagination.has_prev %}
                <a class="btn btn-primary float-left" href="{{url_for('blog.home', num=pagination.prev_num if pagination.prev_num > 1 else None)}}">&larr; Newer Posts</a>
            {% endif %}
        </div>
      {% endblock content %}
      </div>
    </div>
  </div>
  <hr>
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-linkedin-in fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="{{config.BLOG_GITHUB_LINK}}">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; {{request.headers.Host}} 2019</p>
        </div>
      </div>
    </div>
  </footer>
  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Custom scripts for this template -->
  <script src="/static/js/clean-blog.min.js"></script>

 <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/a11y-dark.min.css">
              <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/highlight.min.js"></script>
              <script src="//cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.6.0/highlightjs-line-numbers.min.js"></script>
              <script>
                document.addEventListener('DOMContentLoaded', (event) => {
                  document.querySelectorAll('pre code').forEach((block) => {
                    hljs.highlightBlock(block);
                    hljs.lineNumbersBlock(block);
                  });
                });
              </script>
</body>
</html>

blog/templates/front/contact.html
{%set background_image='contact-bg.jpg' %}
{% extends "front/index.html" %}

{% macro input(field) -%}
  <div class="control-group">
        <div class="form-group floating-label-form-group controls">
          <label>{{field.label.text}}</label>
          {{field(class_="form-control", placeholder=field.label.text)}}
          {% if field.errors -%}
            <p class="help-block text-danger"> {{field.errors.0}}</p>
          {% endif %}


        </div>
      </div>
{%- endmacro %}

{% block content %}
{% if success_send %}
<div class="alert alert-secondary" role="alert">
<p>Mail has been sent. Thank you for getting in touch!
 I will get back to you shortly.
 </p>
<p>Have a great day, {{form.name.data}}!</p>
</div>
{% else %}
<form method="POST">
  {{input(form.name)}}
  {{input(form.email)}}
  {{input(form.message)}}

  {{form.recaptcha}}
  <br>
    <div id="success"></div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
    </div>
  </form>
{% endif %}
{%endblock %}

blog/templates/front/index.html
{%set title = page.title %}
{% extends "front/base.html" %}

blog/templates/front/login.html
{% extends "front/index.html" %}

{% macro input(field) -%}
  <div class="control-group">
        <div class="form-group floating-label-form-group controls">
          <label>{{field.label.text}}</label>
          {{field(class_="form-control", placeholder=field.label.text)}}
          {% if field.errors %}
          <p class="help-block text-danger"><ul role="alert"><li>{{field.errors.0}}</li></ul></p>
          {% endif %}
        </div>
      </div>
{%- endmacro %}

{% block content %}

<form method="POST">
  {{input(form.username)}}
  {{input(form.password)}}
  {{form.recaptcha}}
  <br>
    <div id="success"></div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
    </div>
  </form>

{%endblock %}

blog/templates/front/page.html
{% extends "front/index.html" %}
 {% block content %}

 {{page.text | safe}}
 {%endblock %}